name: WorldPass
version: '1.0-SNAPSHOT'
main: fr.jessee.worldPass.WorldPass
api-version: '1.20'
authors: [ Jessee_Dantonio ]

commands:
  worldpass:
    description: test
    usage: /worldpass
    default: true
    permission-message: You do not have permission!
